/**
 * Created by S N Rao on 2/21/2017.
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t
 *
 */
public class FindTheDifferenceLeetCode {

    //Hashmap is the straighforward way. This is a no extra space bit manipulation method. Same as finding the only
    //integer in array that doesn't occur twice.
    public static char findTheDifference(String s, String t) {
        char added=0;
        for(int i=0;i<s.length();i++){
            char cs=s.charAt(i);
            char ct=t.charAt(i);
            added ^=cs;
            added ^=ct;
        }
        added^=t.charAt(t.length()-1);
        return added;
    }

    public static void main(String args[]){
        System.out.print(findTheDifference("abcdef","aebcgfd"));
    }
}
